### ISSUE TITLE
How to make this work with html templates?

### ISSUE THREAD

**Issue by hybrisCole** [twbs/bootlint#190]
I want to use this with https://github.com/yeoman/generator-angular, but lint is ranting because the templates obviously does not have <! doctype> and other stuff (they are just plain html). 

Is there any config I can setup to make it ignore those rules on templates?

Regards

**Comment by N4M3Z** [comment]
In my opinion this really needs to be configurable through other means than just the command line. Either by comment tags within the html file itself or a dotfile in project root. Command line arguments change global behavior if bootlint is being run from an editor like Atom.

**Comment by cvrebert** [comment]
@N4M3Z See #371.
