### ISSUE TITLE
CSP error in bookmarklet

### ISSUE THREAD

**Issue by JayHoltslander** [twbs/bootlint#201]
In the console on Safari 8.0 on OS X.10.1

> Refused to load the script 'http://maxcdn.bootstrapcdn.com/bootlint/latest/bootlint.min.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com"

**Comment by XhmikosR** [comment]
I'm not sure there's something we can do here. It's a general issue and expected if a site is using CSP.
