### ISSUE TITLE
CLI broken after #178

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootlint#211]
https://travis-ci.org/MaxCDN/bootstrap-cdn/builds/44725825

The cause seems to be #178. After reverting that in https://github.com/twbs/bootlint/compare/test-revert-178, Bootlint runs fine then (locally on my Windows VM but it should on Travis too). 0.8.0 also works fine which makes sense since it doesn't inlcude #178.

/CC @hnrch02

**Comment by hnrch02** [comment]
Yeah, that's due to the CLI waiting on stdin because `process.stdin.isTTY` seems to always be `undefined` when using `child_process.exec` which shelljs/make#exec uses.

**Comment by XhmikosR** [comment]
Thanks! I'll wait for 0.9.2 to verify and delete that other branch I made here with the revert.

**Comment by XhmikosR** [comment]
Err, I was slow this time :p Everything seems to be fine now.
