### ISSUE TITLE
Does bootlint ignore IE conditional HTML comments?

### ISSUE THREAD

**Issue by Profforgr** [twbs/bootlint#214]
It seems like, that bootlint can not understand the meta tags in "if IE" clause.

It warns:
```javascript
bootlint:  W002  `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
```

But i have X-UA-Compatible `<meta>` tag:

```
<!--[if IE]>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
```

**Comment by cvrebert** [comment]
It's completely unnecessary to wrap that `<meta>` tag in an IE conditional comment.

**Comment by cvrebert** [comment]
And to clarify, Bootlint doesn't understand or attempt to parse IE conditional comments; it would complicate the code. IE conditional HTML comments are generally a last resort anyway, and have been deprecated or removed in "recent" versions of IE.

@hnrch02 Okay with closing this?

**Comment by Profforgr** [comment]
> It's completely unnecessary to wrap that <meta> tag in an IE conditional comment.

Not sure what's the reason to make other browsers read it. And some browsers may use it for other purposes, which is not needed here. It's also easier to wrap all IE-based code into conditional HTML comment for visibility, like this:

```html
	<!-- Force latest IE rendering engine or ChromeFrame if installed -->
	<!--[if IE]>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta http-equiv="Content-Language" content="ru-ru" />
	
	<meta http-equiv="imagetoolbar" content="no"/>
    <meta http-equiv="MSThemeCompatible" content="no"/>
	<![endif]-->
```

> Bootlint doesn't understand or attempt to parse IE conditional comments; it would complicate the code.

Bad.

> IE conditional HTML comments are generally a last resort anyway, and have been deprecated or removed in "recent" versions of IE.

I am pretty sure there will be very little % of people using "recent versions of IE", but there are a big % of people using older versions, which support IE conditional HTML comments and we need to make website fine for them.



Nervermind, i think anyone who is using HTML conditional comments for this will understand, that bootlint just ignores HTML comments or will find this issue and understand then. Closing.

**Comment by cvrebert** [comment]
> And some browsers may use it for other purposes, which is not needed here.

They don't. (I would challenge you to find a counterexample.) See the HTML5 spec itself: https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-x-ua-compatible It's only used by IE (and the Chrome Frame plugin for IE). All other browsers ignore it completely.

**Comment by cvrebert** [comment]
> I am pretty sure there will be very little % of people using "recent versions of IE", but there are a big % of people using older versions, which support IE conditional HTML comments and we need to make website fine for them.

Right, I mean, even Bootstrap advises IE conditional comments for html5shim and respond.js. But Bootlint doesn't currently attempt to lint for either of those, and nothing else Bootstrap-related needs to be in conditional comments, so we don't currently attempt to parse them.
