### ISSUE TITLE
.alert-dismissable not accepted by E033

### ISSUE THREAD

**Issue by mastertinner** [twbs/bootlint#218]
**E033 `.alert` with dismiss button must have class `.alert-dismissible`** currently doesn't support the class '.alert-dismissable' instead of '.alert-dismissible'. In Bootstrap though, these are used as synonyms.

**Comment by cvrebert** [comment]
But the `alert-dismissable` spelling is a misspelling and has been deprecated.

**Comment by mastertinner** [comment]
Oh ok, thanks for the info and sorry for the troble then.
