### ISSUE TITLE
Nesting columns triggers error

### ISSUE THREAD

**Issue by hebbet** [twbs/bootlint#225]
Bootlint doesn't support Nesting columns

http://getbootstrap.com/css/#grid-nesting

example html:
http://jsfiddle.net/4wd9t9nt/

getting E013

**Comment by zacechola** [comment]
Can you provide anymore information about browser, Bootlint version, etc.? I can't recreate E013 with that fiddle's output. E013 and E014 deal specifically with linting the correctness of nested columns.

**Comment by hebbet** [comment]
Chrome 41, Bootlint 0.10.0 using the snippet.

**Comment by cvrebert** [comment]
Unable to reproduce with http://jsfiddle.net/ubf6tvpn/1/ on either Chrome 40 or 42, both on OS X.
