### ISSUE TITLE
Enforce more carousel constraints

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#227]
* `.carousel` must contain a `.carousel-inner`
* `.carousel-inner` must contain exactly one `.item.active`

X-Ref: https://github.com/twbs/bootstrap/pull/15782

**Comment by borja** [comment]
Sorry for re-open this issue.
But...

https://github.com/twbs/bootlint/wiki/E041
https://getbootstrap.com/docs/4.0/components/carousel/

Should check `.carousel-item` 
instead of just `.item`

Best regards.

**Comment by cvrebert** [comment]
@borja This issue is from Bootstrap v3. For v4, please open a new issue.
