### ISSUE TITLE
Consider using parse5 for fully standard-compliant HTML parsing

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#249]
As https://github.com/inikulin/parse5/issues/30 has now been fixed, we should consider using parse5 with cheerio, as parse5 is fully standard-compliant, whereas htmlparser2 has some known issues that make it non-compliant.

**Comment by cvrebert** [comment]
Well, there's https://github.com/inikulin/whacko, a Cheerio fork that uses parse5, but there might be ecosystem drawbacks.

**Comment by kkirsche** [comment]
I'd be happy to convert to whacko but it throws an error for example with the following fixture for `Document declares a non-HTML5 DOCTYPE` for:
https://github.com/twbs/bootlint/blob/master/test/fixtures/doctype/html5-legacy.html#L1

**Comment by cvrebert** [comment]
Closing per https://github.com/twbs/bootlint/pull/251#issuecomment-76586858
