### ISSUE TITLE
W002 check should be case insensitive

### ISSUE THREAD

**Issue by hostep** [twbs/bootlint#259]
Over at the html5boilerplate project, they recently changed the recommended `x-ua-compatible` meta tag to be lowercase: https://github.com/h5bp/html5-boilerplate/issues/1656

**Comment by sb4m** [comment]
Hi,
Just spend some time with an upper case missing

$('head>meta[http-equiv="X-UA-Compatible"]').attr('content').match(/IE=edge/i) != null

And will handle the Chrome version (chrome=1) even it's deprecated

**Comment by cvrebert** [comment]
> And will handle the Chrome version (chrome=1) even it's deprecated

We want to warn about it. See #152.

**Comment by sb4m** [comment]
agree with you but this tricks make it's right with no case sensitive

**Comment by cvrebert** [comment]
Meh. Any capitalization besides `IE=edge` or `ie=edge` is bizarre/insane.

**Comment by indrakaw** [comment]
Too bad, emmet will generate `<meta http-equiv="X-UA-Compatible" content="ie=edge">` when i typed `!<tab>`. And I still having error and have to change `ie=edge` into `IE=edge`.
