### ISSUE TITLE
Create bower package

### ISSUE THREAD

**Issue by evilebottnawi** [twbs/bootlint#268]

**Comment by cvrebert** [comment]
I'm -1 on principle given how Bower doesn't seem sufficiently powerful/useful as a package manager in general. But I'm not BDFL anymore, so...

CC: @hnrch02

**Comment by zacechola** [comment]
But, they finally figured out what to do with main, @cvrebert!

**Comment by hnrch02** [comment]
Don't really see a reason for it now and if @cvrebert doesn't want it I don't think I want it. Also you could just use the [GitHub shorthand](http://bower.io/docs/api/#install).
