### ISSUE TITLE
W002 IE conditional tags

### ISSUE THREAD

**Issue by evilebottnawi** [twbs/bootlint#269]
I have code for ie in head:
```html
<!--[if IE ]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<![endif]-->
```
But got error:
W002  `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

It is normal? or not?

**Comment by cvrebert** [comment]
That's normal. We don't parse IE conditional HTML comments, and it's completely unnecessary to enclose this meta tag in them.

**Comment by evilebottnawi** [comment]
@cvrebert thanks
