### ISSUE TITLE
Add check for btn usage within .navbar-nav

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#273]
> ### [Context-specific usage](http://getbootstrap.com/components/#navbar-buttons)
> [...] However, neither `.navbar-btn` nor the standard button classes should be used on `<a>` elements within `.navbar-nav`.

**Comment by kkirsche** [comment]
PR sent. Any help on figuring out why the tests are saying that there are no assertions though would be greatly appreciated. The verification and fixture work correctly, just not the test file.
