### ISSUE TITLE
Check that modals have a tabindex attribute

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#290]
Refs https://github.com/twbs/bootstrap/issues/16677

**Comment by cvrebert** [comment]
Refs https://github.com/twbs/bootstrap/issues/17105

**Comment by jcs12311** [comment]
@cvrebert 
Oh man, my english it bad, but i know tabindex= "-1" not optional.
i just try to explain why use tabindex="-1".
```
this.$element.on('keydown.dismiss.bs.modal', $.proxy(function (e) {
        e.which == 27 && this.hide()
      }, this))
```
so, modal has no focus without tabindex, it also can't trigger 'keydown.dismiss.bs.modal'.
when you see this, and know what i am say, just delete this comment.
