### ISSUE TITLE
Use native Travis caching system instead of our DIY cache

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#310]

**Comment by XhmikosR** [comment]
@cvrebert: https://github.com/twbs/bootlint/tree/travis-cache

For gems, we'll need bundle. Do you want me to add that too?

**Comment by cvrebert** [comment]
@XhmikosR Yes please.

**Comment by XhmikosR** [comment]
All right, I'll make a PR when I'm done in a few minutes.
