### ISSUE TITLE
Unable to locate JQuery when using Meteor

### ISSUE THREAD

**Issue by jscharf** [twbs/bootlint#311]
I am using meteor and the grunt-cli and got the following error message after running the bootlint task:

>W005 Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work; however, you might not be using Bootstrap's JavaScript

I think it might be because it's meteor and it loads the files differently, but that's just a guess. In my `.meteor/packages` file, I can see the entry for `twbs:bootstrap`.

**Comment by zacechola** [comment]
That is exactly why. Our mechanism for checking jQuery is pretty naive. You will want to [disable that problem ID](https://github.com/twbs/bootlint#on-the-command-line).
