### ISSUE TITLE
Add check for attempted nesting of .form-group

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#315]
Refs https://github.com/twbs/bootstrap/pull/17897

**Comment by tclindner** [comment]
Here are the docs I would like to add to the wiki.

Update home.md with 
* [[E050]] (`.form-group`s cannot be nested)

Add E050.md
# E050

## `.form-group`s should not be nested.

In Bootstrap v3, `.form-group`s do not support nesting. 

Wrong:
```html
<div class="form-group">
    …
    
    <div class="form-group">
        …
    </div>
</div>
```

Right:
```html
<div class="form-group">
    …
</div>
<div class="form-group">
    …
</div>
```
