### ISSUE TITLE
using offset in class causes E013

### ISSUE THREAD

**Issue by jphillips05** [twbs/bootlint#316]
```html
...
<div class="container">
    <div class="row">
        <div class="col-lg-offset-2"><span>test</span></div>
    </div>
</div>
...
```
throwing: E013
I am doing this wrong or is there a work around for this?

**Comment by zacechola** [comment]
Nope. Column need to be set along with the offset.

```html
<div class="container">
    <div class="row">
        <div class="col-lg-offset-2 col-lg-2"><span>test</span></div>
    </div>
</div>
```

[See how in the column offset examples in the docs](http://getbootstrap.com/css/#grid-offsetting) the columns are all defined, and where all 12 columns are used in a row, the columns and offsets equal 12.
