### ISSUE TITLE
Check that .modal has role="dialog"

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootlint#318]

**Comment by tclindner** [comment]
Hi @cvrebert let me know if you have any questions/concerns with the associated PR! 

Here are the docs I would like to add to the wiki

Update home.md with:
* [[E048]] (`.modal` missing `[role="dialog"]`)

Add E048.md 
# E048

## `.modal` should always have a `role` attribute with a value of `dialog`.

For accessibility reasons, all modals (i.e. elements with the `.modal` class) must have a `role` attribute. The value should be set equal to `dialog`.

Wrong:
```html
<div class="modal" tabindex="-1">
  ...
</div>
```

Right:
```html
<div class="modal" tabindex="-1" role="dialog">
  ...
</div>
```
