### ISSUE TITLE
CLI script in version 0.14.1 silently fails

### ISSUE THREAD

**Issue by techxplorer** [twbs/bootlint#333]
Hi,

I'm not familiar enough with node or with the bootlint app specifically, so I'm not sure what exactly is going wrong. I'll share what I've found, in the hope that others can find a solution. 

Today I installed the latest version, 0.14.1, of the bootlint app using `npm -g install bootlint`. When I run the CLI script it silently fails. That is, it doesn't check any files, it doesn't respond to command line options, it just exits with a zero status code. 

If I manually copy the `cli.js` file from the 0.13.0 release into the `node_modules/bootlint/src` directory, bootlint appears to work as expected. Files are checked, etc. 

This suggests that there is something wrong with the latest version of the `cli.js` script. I hope this is enough for someone more experienced than I, to identify the root cause and fix the issue.

With thanks. 

-Corey

**Comment by cvrebert** [comment]
CC: @XhmikosR @hnrch02

**Comment by cvrebert** [comment]
CC: @kkirsche

**Comment by cvrebert** [comment]
Caused by #253. The fact that we lack an external test of the CLI's output certainly didn't help things.

**Comment by cvrebert** [comment]
I am happy to incorporate any feedback on #335 into a new PR, but for now I'm shipping it as-is as a critical bugfix.
