### ISSUE TITLE
E042 ".form-control cannot be used on non-textual <input>s" does not account for <input>s without type attr

### ISSUE THREAD

**Issue by dbkaplun** [twbs/bootlint#341]

**Comment by cvrebert** [comment]
An `<input>` without a `type` should be its own warning: http://getbootstrap.com/css/#callout-input-needs-type

**Comment by tclindner** [comment]
Here are the docs I would like to add to the wiki.

Update home.md with 
* [[W017]] (`input` missing `type` attribute)

Add W017.md
# W017

## Found one or more `<input>`s missing a `type` attribute.

It's best-practice to always set a type on `<input>`s. If a `<input>` lacks a type attribute, it defaults to being a `type="text"`. Please note that `<input>`s will only be fully styled if their `type` is properly declared. Bootstrap supports most common form control, text-based input fields. It includes support for all HTML5 types: `text`, `password`, `date time`, `datetime-local`, `date`, `month`, `time`, `week`, `number`, `email`, `url`, `search`, `tel`, and `color`.
