### ISSUE TITLE
Check for `X-UA-Compatible` in HTTP headers

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootlint#343]
Many people including me, send the X-UA-Compatible header instead of adding the meta tag.

I think it would be a big improvement if we could check for the header if the meta tag doesn't exist. Not sure which has precedence though.

**Comment by cvrebert** [comment]
How on earth would we check for that?

**Comment by XhmikosR** [comment]
I don't know if it's possible to parse the HTTP headers via Javascript for
he browser version. But I thought I'd bring it up.
