### ISSUE TITLE
Update home page doco to explain how easy bookmarklets are

### ISSUE THREAD

**Issue by aavmurphy** [twbs/bootlint#346]
Please explain "bookmarklets" better on the home page intro
- I had never heard of them, so ignored them at first
- They are _very_ easy to use, and run after the Javascript. Or after other interactions like clicking on things), which is exactly what I needed.

I was about to raise a Bootstrap Issue, found a similar one that had been closed due to 'you didnt lint first'. So thought I should check first. Blow me if I didn't find some (poorly documented) things that fixed it.

Something like.

You can run bootlint _very_ easily from a web browser bookmark (or "bookmarklet"). 
- Just create a bookmark (of any page). 
- Edit the bookmark, and give this (....) as the URL. 
- Then just click on it when you need it
- View the debug output in the developer console
- e.g. on Chrome: Options | More Tools | Developer Console | "Console" tab) 

Best of all, you can run it at any time, on any page, by just clicking the bookmark , e.g. 
- after the Javascript has run
- after AJAX, clicking things, or other page interactions.

**Comment by zacechola** [comment]
Perhaps the Wikipedia link isn't sufficient?
