### ISSUE TITLE
Remove dist from source and add npmignore file

### ISSUE THREAD

**Issue by tclindner** [twbs/bootlint#354]
The goal of this is to remove dynamically generated files from source control.

Items we need complete
- Update .gitignore to ignore dist/
- Remove dist/ from source control
- Add an empty .npmignore file (This will allow us to include the dist directory when publishing the node module, but exclude it from source control.)
- Remove dist references in README.md and CONTRIBUTING.md

**Comment by cvrebert** [comment]
As with Bootstrap, we include `dist/` for the convenience of users, so as to not require them to setup their own transpilation toolchain when using the package in simple cases.
