### ISSUE TITLE
Are col-*-* classes supposed to be allowed on <table> related elements?

### ISSUE THREAD

**Issue by chrismbarr** [twbs/bootlint#376]
I see that [rule **E014** specifically allows](https://github.com/twbs/bootlint/blob/6630a83a794ce754476c031cfea7f3e4a143f1df/src/bootlint.js#L738-L747) for `col-*-*` classes to appear on `<col>`, `<td>` and `<th>` elements.  I see no mention of this being allowed in the bootstrap docs or [in the bootlint wiki](https://github.com/twbs/bootlint/wiki/E014).  I also see no tests in bootlint that check for this.

Is this intended?  I only noticed this because I saw a usage of this in a project that I have bootlint running on, and I was surprised that it wasn't flagged.

**Comment by cvrebert** [comment]
Yes, it's intended. https://github.com/twbs/bootstrap/issues/11623 implies that it's supported.
You're right that 747dc1c5e356e91ea3900bc73af68f2a271edf86 neglected to include a test and that the docs ought to mention this case.
