### ISSUE TITLE
How to style file upload button conforming to bootlint?

### ISSUE THREAD

**Issue by Herst** [twbs/bootlint#380]
Following https://blueimp.github.io/jQuery-File-Upload/ I would use a span styled as a button to put over an oversized file upload input in order to style it (that's the easiest way if you want to support older browsers as well). Now bootlint does not like it if I style a span as a button, what should I do? Use a label without a "for" for that?

**Comment by cvrebert** [comment]
Bootstrap v3 doesn't provide/suggest a way to style `<input type="file">`s, hence Bootlint won't deem as valid the constructs you mentioned.
Bootstrap v4 may include a proper widget for this; see http://v4-alpha.getbootstrap.com/components/forms/#file-browser

Pragmatically speaking, ignoring the warning in your case is probably okay.
