### ISSUE TITLE
Menu disappears when clicking to expand menu

### ISSUE THREAD

**Issue by solo61282** [twbs/bootlint#382]
If you visit www.jewelryshopping.com/content.cgi from a mobile device and click on "Browse by Category" instead of expanding the menu and remaining open, it goes to the link cart.cgi, however, if you scroll down as you are putting your finger above "Browse By Category" , the menu properly expands without going to cart.cgi

The goal is to make it so that the first tap of Browse By Category expands the menu and then clicking on it again would then take you to cart.cgi

**Comment by cvrebert** [comment]
Closing since this neither alleges any bug in not requests a feature for Bootlint, and is thus off-topic for this repository.

**Comment by solo61282** [comment]
Hi Chris,

My apologies, was hoping then you could guide me on a place where I can
receive some assistance with this

I appreciate it

Rafael

**Comment by cvrebert** [comment]
For support questions, ask on StackOverflow, IRC, or Slack: https://github.com/twbs/bootstrap/blob/master/README.md#community
To report a bug in Bootstrap, see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports
