### ISSUE TITLE
W001 false positive when using Content-Type meta header

### ISSUE THREAD

**Issue by gemal** [twbs/bootlint#383]
my webpage has:
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`

but I get a W001 error running bootlint on it
I think that a false positive

**Comment by GeNyaa** [comment]
>  content="text/html;

**Comment by gemal** [comment]
@cvrebert can you have a look at the pull request?

**Comment by gemal** [comment]
@cvrebert can you make a new release with this change?
