### ISSUE TITLE
bootstrap v4 col declaration

### ISSUE THREAD

**Issue by jackjameshoward** [twbs/bootlint#397]
For reasons I haven't yet found, in bootstrap v4 you can declare an `col-xs-*` as just `col-*`
see the comparison on these two pages
[v3 grid](getbootstrap.com/examples/grid/)
[v4 grid](https://v4-alpha.getbootstrap.com/examples/grid/ )

Bootlint throws an E013 because of this change. 
I suppose I should ask does bootlint support any v4 changes

**Comment by jackjameshoward** [comment]
I've just seen a response to a similar question #377. Which clearly states bootlint isn't v4 compatible.

**Comment by cvrebert** [comment]
Correct.

**Comment by Herst** [comment]
@jackjameshoward If you are interested you can help me with #410
