### ISSUE TITLE
Fix coverage

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootlint#404]
It seems coverage is broken for a long time https://coveralls.io/github/twbs/bootlint

Maybe we should try nyc?

/CC @bardiharborow @cvrebert

**Comment by tclindner** [comment]
Hi @XhmikosR I would highly recommend nyc. I've used it on a few projects. It has a lot of features. I've only scratched the surface on using them 🤓 

Here is the npm script I've been using on [npm-package-json-lint](https://github.com/tclindner/npm-package-json-lint)
`"coverage": "nyc --extension .js --check-coverage --lines 99 --branches 97 --functions 96 npm test"`

**Comment by XhmikosR** [comment]
Yeah, that is what I have already switched to in #405. I just need some help to fix nodeunit and qunit there :)

**Comment by tclindner** [comment]
Nice!
