### ISSUE TITLE
Direct input causes Oops

### ISSUE THREAD

**Issue by gemal** [twbs/bootlint#412]
`Oops! there is a problem with the API, please check again later.`

when I use:
http://www.bootlint.com/
with the Direct Input

Try to take the source from:
http://dinnerbooking.com/dk/da-DK/gc5/gavekort-kob
and use the source as input

**Comment by cvrebert** [comment]
We don't maintain that site. See https://github.com/twbs/bootlint/blob/master/README.md#third-party-service
