### ISSUE TITLE
remove W002 as no longer needed

### ISSUE THREAD

**Issue by jmhodges** [twbs/bootlint#413]
Since https://github.com/twbs/bootstrap/issues/21476, bootstrap is no longer going to be support IE 9, and the warning about missing X-UA-Compatibles are no longer necessary.

So, W002 can go away, yeah?

**Comment by Herst** [comment]
Bootstrap 3 supports IE9.

**Comment by jmhodges** [comment]
Ah, so would this be a for bootstrap 4, then!

**Comment by Herst** [comment]
ATM, Bootlint is just for Bootstrap 3, there seem to be official plans for Bootstrap 4 support. I made an attempt at #410.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootlint/issues/304
