### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by DanielRuf** [twbs/bootlint#418]
https://github.com/twbs/bootlint/releases

Would be good to have the 74 commits in a new release.

**Comment by XhmikosR** [comment]
Yeah, after making all the changes, I was getting total failures in grunt-bootlint and thus I removed the tags. Any help would be welcome!

**Comment by XhmikosR** [comment]
For reference https://travis-ci.org/twbs/grunt-bootlint/jobs/402012020

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootlint/releases/tag/v0.15.0
